# -*- coding: utf-8 -*-
"""finetune_navvit_swin.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ys_mwkVSFqHISquC-ncyWqz8k1F-iSMT
"""

!pip install navit-torch

import torch
from torch.optim import Adam
from torch.utils.data import DataLoader
import torch.nn.functional as F
from navit.main import NaViT

from torchvision import datasets, transforms



# Assuming your unlabeled images for pretraining are in a folder structure
from torchvision import datasets, transforms
from torch.utils.data import DataLoader

# Define image transformations
transform = transforms.Compose([
    transforms.Resize((256, 256)),
    transforms.ToTensor()
])

!pip install transformers

from transformers import SwinForImageClassification, AutoImageProcessor
# Load pretrained Swin Transformer
from transformers import SwinForImageClassification, AutoImageProcessor

from transformers import SwinForImageClassification, AutoImageProcessor
from torch.utils.data import DataLoader
import torch
from torch.optim import Adam
from torch.nn import CrossEntropyLoss
from PIL import Image

# Load pretrained Swin Transformer
model_name = "microsoft/swin-tiny-patch4-window7-224"
model = SwinForImageClassification.from_pretrained(model_name, num_labels=4,ignore_mismatched_sizes=True)  # 4 classes
image_processor = AutoImageProcessor.from_pretrained(model_name)

num_augmentations = 450  # Number of augmentations per image
#augment_dataset(root_dir, output_dir, num_augmentations)

from torch.utils.data import Dataset
from torchvision import transforms
from PIL import Image
import os
import random

from torch.utils.data import Dataset
from torchvision import transforms
from PIL import Image
import os
import random

class CustomGroupedDatasetWithLabels(Dataset):
    def __init__(self, root_dir, group_sizes, transform=None):
        """
        root_dir: str, path to the dataset directory (organized into class folders)
        group_sizes: list of int, sizes of groups to create (e.g., [2, 2, 1])
        transform: torchvision.transforms, transformations to apply to the images
        """
        self.root_dir = root_dir
        self.transform = transform
        self.image_files = []
        self.labels = []

        # Map folder names to numeric labels
        self.class_to_idx = {cls_name: idx for idx, cls_name in enumerate(os.listdir(root_dir))}

        # Collect all image paths and their labels
        for cls_name, label in self.class_to_idx.items():
            print(cls_name)
            print(label)
            class_dir = os.path.join(root_dir, cls_name)
            if os.path.isdir(class_dir):
                for img_name in os.listdir(class_dir):
                    if img_name.endswith(('.png', '.jpg', '.jpeg')):
                        self.image_files.append(os.path.join(class_dir, img_name))

                        self.labels.append(label)

        # Shuffle images and labels together
        combined = list(zip(self.image_files, self.labels))
        random.shuffle(combined)
        self.image_files, self.labels = zip(*combined)

        # Create groups of images and labels based on group_sizes
        self.group_sizes = group_sizes
        self.groups = []
        idx = 0
        for size in group_sizes:
            group_files = self.image_files[idx:idx + size]
            group_labels = self.labels[idx:idx + size]
            self.groups.append((group_files, group_labels))
            idx += size

    def __len__(self):
        return len(self.groups)

    def __getitem__(self, idx):
        """
        Returns a tuple (images, labels), where:
          - images: List of tensors (C, H, W) for the group
          - labels: List of labels for the group
        """
        group_files, group_labels = self.groups[idx]
        images = []
        labels = []

        for img_path, label in zip(group_files, group_labels):
            img = Image.open(img_path).convert("RGB")  # Load image
            if self.transform:
                img = self.transform(img)  # Apply transformations
            images.append(img)
            labels.append(label)

        return images, labels

import torch
from torch.utils.data import DataLoader
from torch import nn, optim
from torchvision import transforms
from transformers import SwinForImageClassification
import os
from PIL import Image
from transformers import SwinModel, AutoImageProcessor
import torch
from torch.optim import Adam
from torch.utils.data import DataLoader
import torch.nn.functional as F
from navit.main import NaViT

from torchvision import datasets, transforms
from torch.utils.data import Dataset

# Dataset and Transform
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5])
])

dataset_dir = "/content/drive/MyDrive/sata_data_augmented_aggressive/"
train_dataset = CustomGroupedDatasetWithLabels(root_dir=dataset_dir,group_sizes = [1, 1, 1] , transform=transform)

# DataLoader
train_loader = DataLoader(train_dataset, batch_size=1, shuffle=True)

# Load Swin Model for Fine-Tuning


# Load pretrained Swin Transformer (without the classification head)
model_name = "microsoft/swin-tiny-patch4-window7-224"
swin_model = SwinModel.from_pretrained(model_name)

device = "cuda" if torch.cuda.is_available() else "cpu"
model.to(device)

# Loss Function and Optimizer
criterion = nn.CrossEntropyLoss()
optimizer = optim.AdamW(model.parameters(), lr=5e-5)

# Training Loop
epochs = 20
for epoch in range(epochs):
    model.train()
    running_loss = 0.0

    for (images, labels) in train_loader:

        images=[img.to(device) for img in images]
        labels=torch.Tensor(labels).long().to(device)
        images = torch.stack(images)

        print(labels.shape)
        images = torch.squeeze(images, dim=1)
        print(images.shape)
        # Forward pass
        print("images",images.shape)
        outputs = model(pixel_values=images)
        print(outputs.logits.shape)
        print(labels.shape)
        loss = criterion(outputs.logits, labels)

        # Backward pass and optimization
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        running_loss += loss.item()

    print(f"Epoch {epoch + 1}/{epochs}, Loss: {running_loss / len(train_loader)}")

# Save Fine-Tuned Model
model.save_pretrained("/content/drive/MyDrive/swin_finetuned2")